SET NOCOUNT ON;
DECLARE @FormId INT = (SELECT FormId FROM MIG.FORM WHERE FormName='WorkOrderInstructionNature');
IF @FormId IS NOT NULL BEGIN
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DATABASE', 'SC_WO_INS_NATURE_LIST', 'TABLE', @FormId, 'LEGACY', 'Category update pending', 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='SC_WO_INS_NATURE_LIST' AND ObjectType='TABLE');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DATABASE', 'SPN_SC_DEL_WI_NATURE_LIST', 'PROC', @FormId, 'LEGACY', 'Category update pending', 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='SPN_SC_DEL_WI_NATURE_LIST' AND ObjectType='PROC');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DATABASE', 'SPN_SC_GET_WI_NATURE_LIST', 'PROC', @FormId, 'LEGACY', 'Category update pending', 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='SPN_SC_GET_WI_NATURE_LIST' AND ObjectType='PROC');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DATABASE', 'SPN_SC_INS_WI_NATURE_LIST', 'PROC', @FormId, 'LEGACY', 'Category update pending', 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='SPN_SC_INS_WI_NATURE_LIST' AND ObjectType='PROC');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DATABASE', 'SPN_SC_UPD_WI_NATURE_LIST', 'PROC', @FormId, 'LEGACY', 'Category update pending', 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='SPN_SC_UPD_WI_NATURE_LIST' AND ObjectType='PROC');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DATABASE', 'SPN_SE_GET_IS_SUPPLY_PORTAL_APPLICABLE', 'PROC', @FormId, 'LEGACY', 'Category update pending', 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='SPN_SE_GET_IS_SUPPLY_PORTAL_APPLICABLE' AND ObjectType='PROC');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'BLL', 'bSecurity.cs', 'BLL', @FormId, 'RETIRING', NULL, 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='bSecurity.cs' AND ObjectType='BLL');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'BLL', 'bWorkInsNatureList.cs', 'BLL', @FormId, 'RETIRING', NULL, 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='bWorkInsNatureList.cs' AND ObjectType='BLL');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DAL', 'sSecurity.cs', 'DAL', @FormId, 'RETIRING', NULL, 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='sSecurity.cs' AND ObjectType='DAL');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'DAL', 'sWorkInsNatureList.cs', 'DAL', @FormId, 'RETIRING', NULL, 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='sWorkInsNatureList.cs' AND ObjectType='DAL');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'UI', 'xpWOInsNatureList.cs', 'UI_FORM', @FormId, 'RETIRING', NULL, 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='xpWOInsNatureList.cs' AND ObjectType='UI_FORM');
INSERT INTO MIG.OBJECT_OWNERSHIP (Layer, ObjectName, ObjectType, FormId, OwnershipCategory, Remarks, CreatedBy, CreatedDate) SELECT 'UI', 'xpWOInsNatureList.Designer.cs', 'DESIGNER', @FormId, 'RETIRING', NULL, 'BatchScript', GETDATE() WHERE NOT EXISTS (SELECT 1 FROM MIG.OBJECT_OWNERSHIP WHERE ObjectName='xpWOInsNatureList.Designer.cs' AND ObjectType='DESIGNER');
END
